name: Azure Build and Deploy
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    name: ACR Registry Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2@main
     
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            
          tags: ${{ secrets.ACR_ENDPOINT }}/reactpy:latest
          file: ./docker-compose.yml
